### ISSUE TITLE
Discuss Alternative Option for Exploring Viability of a Jaeger/Otel Collector

### ISSUE THREAD

**Issue by joe-elliott** [jaegertracing/jaeger-opentelemetry-collector#10]
OpenTelemetry Collector is beginning to take on some of the roles of the Jaeger Collector.  For instance, currently there are efforts to add support for Kafka storage (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/125) as well as sampling (https://github.com/open-telemetry/opentelemetry-collector/issues/500).  

This repo is aimed at exploring the viability of replacing the Jaeger Collector with the OpenTelemetry Collector.  These efforts are very similar and perhaps they could be consolidated.   

One option would be to PR various Jaeger Storage backends into https://github.com/open-telemetry/opentelemetry-collector-contrib.  This would allow the Jaeger team to experiment with a Jaeger/Otel Collector as well as give members of the otel community access to these additional  storage options.

cc @objectiser

**Comment by yurishkuro** [comment]
My preference is to keep storage options in Jaeger codebase. The scope of OpenTelemetry collector, as a project, is to provide collection pipeline leading to different backends, so Jaeger storage backends don't really belong there.

**Comment by joe-elliott** [comment]
@tigrannajaryan would be able to speak more authoritatively, but I believe one of the purposes of the otelcol-contrib repo is to provide a way to add useful processors/exporters/receivers that don't necessarily belong in core.

I believe these additions would be welcome.

**Comment by tigrannajaryan** [comment]
Exporters which are useful for large audiences are welcome in contrib (highly subjective, I know). If it is something uniquely specialized the preference is to put it elsewhere.

If you intend to have a custom build of the Collector (what you have in this repo) you are probably better served by keeping your specialized exporter here. This will make maintenance easier (otherwise it is a 2-step process).

**Comment by pavolloffay** [comment]
I lean towards @yurishkuro comment. It does not make sense to host Jaeger storage implementation in OTEL repository and consequently I would avoid splitting of storage implementation and build of the final executable into multiple repositories. It makes the project management harder (e.g. we want to also assure the query version is compatible with the collector)

**Comment by pavolloffay** [comment]
I am closing this the Jaeger OTEL collector has been moved to https://github.com/jaegertracing/jaeger/tree/master/cmd/opentelemetry-collector
