### ISSUE TITLE
Implement Jaeger query as a receiver

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-opentelemetry-collector#13]
Jaeger query can be implemented as a receiver.

This is also related to how all-in-one can be implemented: https://github.com/jaegertracing/jaeger-opentelemetry-collector/issues/12

Receiver docs: https://github.com/open-telemetry/opentelemetry-collector#config-receivers

**Comment by yurishkuro** [comment]
Why does query need to be changed at all? Its scope does not overlap with OTC in any aspects.

**Comment by pavolloffay** [comment]
There might be some overlap. It depends on how we want to build all-in-one #12. The all-in-one can link jaeger-otel-collector and jaeger-query and just wire the configuration. Or it could link configure the query as otel receiver.

**Comment by pavolloffay** [comment]
I am closing this for now. We can re-evaluate later once we base all-in-one based on the otel-collector.
