### ISSUE TITLE
Move to jaegertracing/jaeger repo

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-opentelemetry-collector#8]
This project could live in the main jaeger repository https://github.com/jaegertracing/jaeger. It simplifies workflow (e.g. if changes in the main repo are required) and project management (releasing, versioning).

**Comment by yurishkuro** [comment]
I would like that, but wouldn't it create circular dependencies, considering that OTel imports jaeger code?

**Comment by pavolloffay** [comment]
A good question. I will investigate if/how it could be done. The other question is versioning. In the main repository, it will have to follow the version schema as other jaeger components once it is included in the release pipeline.

Then we should also define some acceptance criteria when the code could be migrated. For example:

* use collector in crossdock

Any more ideas?

**Comment by objectiser** [comment]
Firstly, does moving to the main repo imply replacing the current collector? Or would the WIP jaeger-otc be kept as a separate component?

I think an acceptance criteria for the jaeger-otc replacing the current collector is that OTC must have reached 1.x.

**Comment by pavolloffay** [comment]
We can move before reaching 1.x and just exclude it from the release and just publish latest version.
